# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-08 23:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='logos/%Y/%m', verbose_name='商标图片')),
                ('desc', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='商标描述')),
                ('vote_nums', models.IntegerField(default=0, verbose_name='投票数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '商标',
                'verbose_name': '商标',
            },
        ),
    ]
