# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-08 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logos',
            name='pic',
            field=models.ImageField(upload_to='logos', verbose_name='商标图片'),
        ),
    ]
