# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-09 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voters', '0001_initial'),
        ('logos', '0002_auto_20190808_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logos.Logos', verbose_name='图标')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.WXVoters', verbose_name='微信选民')),
            ],
            options={
                'verbose_name': '微信选票',
                'verbose_name_plural': '微信选票',
            },
        ),
    ]
