# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-09 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WXVoters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='微信openid')),
                ('headimgurl', models.URLField(max_length=100, verbose_name='头像url')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
            ],
            options={
                'verbose_name': '微信选民',
                'verbose_name_plural': '微信选民',
            },
        ),
    ]
