# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-09 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_auto_20190809_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxvoters',
            name='headimgurl',
            field=models.URLField(max_length=500, verbose_name='头像url'),
        ),
    ]
